### PR TITLE
add no-multiple-empty-lines

### PR DESCRIPTION
**Pull request by qknudsen**
discussion here: https://github.com/doordash/frontend-standards/issues/14

### CODE REVIEW

**Comment by marknach** [comment]
ah. here we go

**Review by marknach — APPROVED** [review]

**Comment by qknudsen** [comment]
oh, i probably need to up the package.json version as well.  

also, will need to publish after merge.  @marknach or @ryngonzalez, have we just been handling this by publishing from local?

**Comment by ryngonzalez** [comment]
@qknudsen yeah, from what i know that's how we've been doing it

**Comment by ryngonzalez** [comment]
(I actually haven't published before)

**Comment by qknudsen** [comment]
> @qknudsen yeah, from what i know that's how we've been doing it
> (I actually haven't published before)

Ok, I suppose it doesn't need to be done here anyways.  Just won't be able to remove the lint rule from doorstep until we publish.

**Pull request merged**
