### PR TITLE
Proposed rule changes

### PR DESCRIPTION
**Pull request by danehansen**
proposed rule changes, which are up to debate of course:
- `default-case`: there are legit circumstances where you do not want a default case for a switch statement. proposal is to reduce this rule from `error` to `warning`.
- `spaced-comment`: my editor, and i suspect others' editors, when using the quick keys to comment out lines and blocks, does not make a space by default. i don't care to waste time with manually doing this, plus IT DOESN'T MATTER. proposal is to turn this rule off completely.
- `arrow-body-style`: my personal belief is that this rule should actually be changed to require braces at all times, for the same reason that braces for if/else statements are required, so that future additions can be made easily and for clearer readability. but based on how much i see the braceless version of these used, i assume i would get downvoted on that one so i propose to just turn this rule off completely so everyone can use them if/when they want.
- `no-did-update-set-state`: this rule means well, but i have a situation now where the work around would be completely convoluted, and this case would not be calling a re-render very frequently, so i believe the lesser of the evils is to have the logic in the `componentDidUpdate` function. i could see this situation happening again in the future. proposal is to reduce this rule from `error` to `warning`

@ajgrover

### CODE REVIEW

**Comment by alex-grover** [comment]
- `default-case`: can you give an example? I have only seen `switch`es with legitimate `default`s
- `spaced-comment`: sure, it's probably configurable but doesn't matter at the end of the day
- `arrow-body-style`: I'm down to enforce braces. I write them without but agree with the rationale
- `no-did-update-set-state`: sure, what's the current case (just for posterity)?

**Comment by danehansen** [comment]
@ajgrover 
`default-case`: due to some refactoring since creating this PR, that case no longer exists, but it was something like this:

```
.catch(error) {
  if (error.status === 400) {
    switch (error.message) {
      case 'specific error message':
        return promiseInstance
      case 'another specific error message':
        return differentPromiseInstance
  }
   throw error
}
```

`no-did-update-set-state`: https://github.com/chillbear/doorstep-django/blob/5b2bacf8752e9f5a17336735312d57af225f4421/static/src/consumer/shared/Login/Input/index.js#L43-L50

**Comment by ymmn** [comment]
#### `default-case`

the reasoning at http://eslint.org/docs/rules/default-case is 

> The thinking is that it’s better to always explicitly state what the default behavior should be so that it’s clear whether or not the developer forgot to include the default behavior by mistake.

they also show example of how you're supposed to skip defaults under this rule. i understand that this looks useless since we don't encountered bugs from this very often.

I did a quick search through our codebase for `switch` statements, and the vast majority of them are in `reducer` files, meaning they actually do need the `default` case (reducers should never return `undefined`). out of the remaining few, it was a toss up for whether or not it needed a `default`. i don't think disabling this rule will lead to a bug in production, but i think it'll lead to more bugs during development where we forget to add a `default` case to a new reducer and have to fix it. so given that it seems to be helpful most of the time, and annoying a few other times, do you think it's worth disabling this rule is overall worth it?

#### `spaced-comment`

I'm a big fan of reading the reasoning behind the rule in the docs: http://eslint.org/docs/rules/spaced-comment

> Whitespace after the // or /\* makes it easier to read text in comments. On the other hand, commenting out code is easier without having to put a whitespace right after the // or /*

I do think this rule enhances the readability of comments (if you don't agree, we should definitely discuss), but I totally see how it's annoying for you to have to manually add spaces, and you shouldn't have to do that. thankfully, this isn't really a tradeoff we have to make since most editors support this functionality anyway. i also really don't like messing with my editor, but at the end of the day it's a one-time cost. I'm totally down to help you setup your editor correctly, or if we even need to, explore running `eslint --fix` automatically pre-commit (which would also fix this problem)

#### `arrow-body-style`

i think a more apt comparison is ternary operators. they're also a syntactic sugar that allows you to have brief one-liners. enforcing braces is a lot like disabling ternary operators, and i think we all like our ternary operators. on the other hand, i can't think of the reasoning to enforce using the shorthand (although i do think it's more readable in some cases). @ryngonzalez what do you think?

**Comment by ymmn** [comment]
for `no-did-update-set-state`, i don't understand the example very well @danehansen. isn't this avoidable by just not storing validation in the state, and calculating it within render?

```
render() {
  const isValid = this._validate()
  // do the rest
}
```

**Comment by danehansen** [comment]
@ymmn 
`default-case`: thats why i'm saying to move it to a warning, not disable it.
`spaced-comment`: i dont find a comment to be any more/less readable if there is a space in front of it. my point here is that its a comment. it doesn't matter. and why should anyone be wasting a second of their time dealing with formatting it, or bothering to change a editor setting to deal with it. i believe our linter should be helping us write better code, not wasting everyone's time about whitespace.
`no-did-update-set-state`: you are right on that one. thanks.

**Comment by ymmn** [comment]
`default-case`: honestly i'm just not a fan of warnings. if we're planning on ignoring something, we should just disable it, rather than have it clutter our eslint output while we have no intention on ever addressing it. the other thing is, i don't think lint rules are meant to be 100% perfect. my feeling is that, if it's 90% right and in the other 10% it's just overly verbose but harmless, i'm ok with it. the only thing i'm never ok with is a decrease in readability, which i dont feel is the case with this one.

`spaced-comment`: i agree with you that comments don't matter to the interpreter. there are lots of things in that category, such as whitespace, `if` vs `switch`, `while` vs `for`, etc. most of our standards have nothing to do with what the interpreter thinks. it's only about the humans who will have to read and maintain the code. comments are actually part of the source code, and in that sense, they matter almost as much as real code imo. so there are two main use cases for comments:
- commented out code
- comment writing out stuff for humans

for commented out code, i don't think we're ever supposed to check it into master anyway (im not sure if we've established this in our frontend code but we definitely don't in our python code). for comments targeting humans, don't you think that if you're spending the time explaining something to a fellow dev that it's worth adding in that extra space if some ppl think it's more readable? i sure would appreciate it :D 

but if you don't see the value in it then fair enough. i'll defer to whatever the rest of the engineers think @christianidylle @ryngonzalez @ajgrover

**Comment by christianidylle** [comment]
`default-case`: As @ymmn mentioned I think this rule definitely has some merit. We should probably keep it. I don't see the harm in. 

`spaced-comment`: Please keep it. Comments should be extremely limited in our codebase in the first place (clean readable code should supersede them). And for the comments that absolutely need to be there I do think that space increases readability as it allows for the eye to more quickly distinguish where the sentence starts. Readability of code should always be a priority as @ymmn mentioned. 

`arrow-body-style`: I don't think using the shorthand version affects readability that much versus braces and it does feel cleaner to me in some cases. I would argue against enforcing braces at all times as it would disallow the use of the arrow body shorthand which is widespread. My vote is to keep this rule in with the `as-needed` setting. 

`no-did-update-set-state`: @ymmn explained it well. Should not disable that one.

**Comment by alex-grover** [comment]
I think the `no-did-update-set-state` could also be done in `componentWillUpdate`, the rationale is that they want to avoid a second render caused by using `setState` right after a render

**Comment by ryngonzalez** [comment]
#### `default-case`:

We should keep it; for the majority case for how we use `switch` statements (writing reducers), we _need_ a `default`. No reason not to be explicit with a comment in the minority cases where no-default is needed.

``` javascript
switch (responseState) {
  API.SUCCESS: …
  API.FAILURE: …
  default:
    // no default needed
}
```

#### `spaced-comment`:

@christianidylle and @ymmn said it well. We should always be vigilant about ensuring our code is readable and understandable to everyone else using the codebase. Every little thing that we do to increase that readability is a good thing, especially if the cost is just a one-time update to our editor settings.

#### `arrow-body-style`:

I think the braces aren't always more readable; there are some cases where readability is hurt by no braces and some where readability is hurt with braces. I would advocate for enforcing braces through code-review as-needed. 

#### `no-did-update-set-state`:

We shouldn't disabled this, as others have said.

**Comment by danehansen** [comment]
@ryngonzalez @christianidylle @ajgrover @ymmn 
`arrow-body-style`: yea i knew enforcing braces wasn't going to fly, which was my original point that we just get rid of that rule, because currently set at `as-needed` forces anybody to remove them if theres only one statement. i dont care to do that any more than anyone else would care to have the braces enforced.

**Comment by christianidylle** [comment]
@danehansen Yeah I think it's fine to turn off the `arrow-body-style` rule and let the coder decide which syntactic sugar to implement for arrow functions. Shouldn't really impact readability or code functionality.

**Pull request merged**
